name: nocturnal_dfu
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  mcumgr_flutter: ^0.4.2
  file_manager: ^1.0.2
  file_picker: ^10.0.0
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  flutter_archive: ^6.0.3
  archive: ^4.0.7
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
